###################################################################################
# Mentor Graphics Corporation
#
###################################################################################

#################
# Attributes
#################
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(0)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(0)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(0)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(0)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(0)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(0)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(0)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(0)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(0)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(0)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(0)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(0)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(0)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(0)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(0)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(0)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(1)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(1)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(1)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(1)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(1)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(1)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(1)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(1)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(1)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(1)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(1)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(1)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(1)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(1)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(1)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(1)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(2)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(2)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(2)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(2)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(2)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(2)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(2)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(2)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(2)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(2)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(2)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(2)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(2)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(2)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(2)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(2)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(3)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(3)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(3)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(3)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(3)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(3)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(3)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(3)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(3)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(3)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(3)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(3)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(3)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(3)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(3)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(3)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(4)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(4)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(4)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(4)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(4)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(4)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(4)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(4)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(4)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(4)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(4)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(4)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(4)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(4)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(4)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(4)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(5)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(5)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(5)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(5)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(5)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(5)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(5)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(5)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(5)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(5)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(5)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(5)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(5)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(5)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(5)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(5)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(6)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(6)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(6)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(6)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(6)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(6)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(6)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(6)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(6)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(6)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(6)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(6)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(6)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(6)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(6)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(6)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(7)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(7)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(7)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(7)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(7)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(7)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(7)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(7)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(7)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(7)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(7)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(7)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(7)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(7)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(7)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(7)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(8)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(8)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(8)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(8)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(8)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(8)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(8)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(8)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(8)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(8)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(8)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(8)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(8)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(8)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(8)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(8)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(9)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(9)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(9)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(9)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(9)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(9)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(9)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(9)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(9)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(9)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(9)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(9)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(9)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(9)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(9)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(9)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(10)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(10)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(10)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(10)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(10)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(10)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(10)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(10)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(10)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(10)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(10)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(10)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(10)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(10)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(10)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(10)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(11)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(11)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(11)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(11)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(11)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(11)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(11)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(11)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(11)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(11)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(11)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(11)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(11)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(11)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(11)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(11)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(12)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(12)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(12)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(12)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(12)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(12)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(12)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(12)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(12)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(12)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(12)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(12)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(12)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(12)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(12)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(12)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(13)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(13)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(13)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(13)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(13)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(13)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(13)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(13)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(13)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(13)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(13)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(13)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(13)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(13)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(13)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(13)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(14)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(14)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(14)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(14)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(14)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(14)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(14)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(14)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(14)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(14)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(14)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(14)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(14)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(14)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(14)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(14)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(15)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(15)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(15)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(15)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(15)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(15)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(15)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(15)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(15)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(15)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(15)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(15)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(15)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(15)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(15)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(15)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(16)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(16)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(16)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(16)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(16)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(16)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(16)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(16)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(16)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(16)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(16)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(16)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(16)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(16)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(16)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/taps(16)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(1)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(1)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(1)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(1)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(1)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(1)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(1)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(1)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(1)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(1)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(1)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(1)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(1)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(1)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(1)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(1)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(2)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(2)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(2)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(2)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(2)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(2)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(2)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(2)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(2)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(2)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(2)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(2)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(2)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(2)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(2)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(2)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(3)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(3)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(3)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(3)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(3)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(3)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(3)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(3)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(3)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(3)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(3)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(3)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(3)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(3)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(3)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(3)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(4)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(4)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(4)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(4)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(4)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(4)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(4)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(4)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(4)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(4)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(4)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(4)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(4)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(4)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(4)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(4)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(5)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(5)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(5)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(5)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(5)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(5)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(5)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(5)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(5)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(5)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(5)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(5)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(5)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(5)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(5)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(5)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(6)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(6)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(6)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(6)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(6)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(6)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(6)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(6)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(6)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(6)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(6)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(6)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(6)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(6)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(6)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(6)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(7)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(7)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(7)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(7)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(7)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(7)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(7)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(7)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(7)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(7)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(7)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(7)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(7)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(7)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(7)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(7)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(8)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(8)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(8)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(8)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(8)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(8)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(8)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(8)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(8)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(8)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(8)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(8)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(8)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(8)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(8)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(8)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(9)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(9)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(9)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(9)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(9)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(9)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(9)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(9)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(9)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(9)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(9)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(9)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(9)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(9)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(9)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(9)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(10)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(10)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(10)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(10)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(10)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(10)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(10)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(10)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(10)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(10)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(10)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(10)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(10)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(10)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(10)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(10)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(11)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(11)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(11)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(11)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(11)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(11)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(11)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(11)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(11)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(11)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(11)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(11)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(11)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(11)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(11)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(11)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(12)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(12)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(12)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(12)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(12)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(12)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(12)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(12)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(12)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(12)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(12)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(12)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(12)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(12)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(12)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(12)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(13)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(13)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(13)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(13)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(13)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(13)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(13)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(13)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(13)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(13)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(13)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(13)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(13)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(13)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(13)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(13)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(14)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(14)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(14)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(14)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(14)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(14)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(14)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(14)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(14)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(14)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(14)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(14)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(14)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(14)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(14)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(14)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(15)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(15)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(15)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(15)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(15)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(15)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(15)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(15)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(15)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(15)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(15)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(15)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(15)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(15)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(15)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(15)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(16)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(16)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(16)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(16)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(16)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(16)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(16)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(16)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(16)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(16)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(16)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(16)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(16)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(16)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(16)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(16)(0) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(17)(15) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(17)(14) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(17)(13) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(17)(12) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(17)(11) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(17)(10) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(17)(9) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(17)(8) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(17)(7) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(17)(6) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(17)(5) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(17)(4) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(17)(3) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(17)(2) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(17)(1) -design rtl 
set_attribute -name logic_block -value "1" -net -type default u_fir/sums(17)(0) -design rtl 
set_attribute -name PLL_TYPE -value "FAST" -instance -type string u_audio_dac/p1/altpll -design rtl 
set_attribute -name INTENDED_DEVICE_FAMILY -value "Cyclone II" -instance -type string u_audio_dac/p1/altpll -design rtl 
set_attribute -name INCLK0_INPUT_FREQUENCY -value "37037" -instance -type integer u_audio_dac/p1/altpll -design rtl 
set_attribute -name COMPENSATE_CLOCK -value "CLK0" -instance -type string u_audio_dac/p1/altpll -design rtl 
set_attribute -name CLK1_PHASE_SHIFT -value "0" -instance -type string u_audio_dac/p1/altpll -design rtl 
set_attribute -name CLK1_MULTIPLY_BY -value "2" -instance -type integer u_audio_dac/p1/altpll -design rtl 
set_attribute -name CLK1_DUTY_CYCLE -value "50" -instance -type integer u_audio_dac/p1/altpll -design rtl 
set_attribute -name CLK1_DIVIDE_BY -value "3" -instance -type integer u_audio_dac/p1/altpll -design rtl 
set_attribute -name CLK0_PHASE_SHIFT -value "0" -instance -type string u_audio_dac/p1/altpll -design rtl 
set_attribute -name CLK0_MULTIPLY_BY -value "14" -instance -type integer u_audio_dac/p1/altpll -design rtl 
set_attribute -name CLK0_DUTY_CYCLE -value "50" -instance -type integer u_audio_dac/p1/altpll -design rtl 
set_attribute -name CLK0_DIVIDE_BY -value "15" -instance -type integer u_audio_dac/p1/altpll -design rtl 


##################
# Clocks
##################
create_clock { aud_bclk } -domain ClockDomain1 -name aud_bclk -period 4.000000 -waveform { 0.000000 2.000000 } -design rtl 
create_clock { clock_27 } -domain ClockDomain0 -name clock_27 -period 4.000000 -waveform { 0.000000 2.000000 } -design rtl 
create_generated_clock { u_i2c_av_config/reg_m_i2c_ctrl_clk/out } -domain ClockDomain3 -name u_i2c_av_config/reg_m_i2c_ctrl_clk/regout -multiply_by 1  -divide_by 2 -source clock_27 -duty_cycle 50.000000  -design rtl 
create_generated_clock { u_audio_dac/reg_lrck_1x/out } -domain ClockDomain2 -name u_audio_dac_reg_lrck_1x/regout -multiply_by 1  -divide_by 3 -source clock_27 -duty_cycle 50.000000  -design rtl 

